name: nlp_exercise
channels:
  - defaults
dependencies:
  - python=3.7
  - pip
  - pip:
    - gensim==4.1.2
    - jupyterlab==3.2.4
    - matplotlib==3.5.0
    - wordcloud==1.8.1
    - nltk==3.6.5
    - numpy==1.21.4
    - pandas==1.3.4
    - scikit-learn==1.0.1
    - tensorflow==2.7.0