name: salamina
channels:
  - defaults
dependencies:
  - python=3.7
  - pip
  - pip:
    - mysqlclient
    - tensorflow
    - numpy
    - pandas
    - mlflow
    - onesaitplatform-client-services
    - mlflow_onesaitplatform_plugin-0.3.2-py3-none-any.whl